<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2012/02/17 14:08:13
return array(

  // dsExtDirectPlugin_module_libs

  // dsExtDirectPlugin_lib
  'dsabstractresultadapter' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/adapter/dsAbstractResultAdapter.class.php',
  'dspropertyresultadapter' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/adapter/dsPropertyResultAdapter.class.php',
  'dsextdirectcontroller' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/controller/dsExtDirectController.class.php',
  'dsextdirectapi' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/dsExtDirectApi.class.php',
  'dsextdirecterrorhandler' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/dsExtDirectErrorHandler.class.php',
  'dsextdirectrouter' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/dsExtDirectRouter.class.php',
  'dsextdirectgenerateapitask' => '/Users/felipedelpozo/Sites/sample/plugins/dsExtDirectPlugin/lib/task/dsExtDirectGenerateApiTask.class.php',

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => '/Users/felipedelpozo/Sites/sample/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseuserformfilter' => '/Users/felipedelpozo/Sites/sample/lib/filter/doctrine/base/BaseUserFormFilter.class.php',
  'baseformfilterdoctrine' => '/Users/felipedelpozo/Sites/sample/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'userformfilter' => '/Users/felipedelpozo/Sites/sample/lib/filter/doctrine/UserFormFilter.class.php',
  'baseform' => '/Users/felipedelpozo/Sites/sample/lib/form/BaseForm.class.php',
  'baseuserform' => '/Users/felipedelpozo/Sites/sample/lib/form/doctrine/base/BaseUserForm.class.php',
  'baseformdoctrine' => '/Users/felipedelpozo/Sites/sample/lib/form/doctrine/BaseFormDoctrine.class.php',
  'userform' => '/Users/felipedelpozo/Sites/sample/lib/form/doctrine/UserForm.class.php',

  // project_model
  'baseuser' => '/Users/felipedelpozo/Sites/sample/lib/model/doctrine/base/BaseUser.class.php',
  'user' => '/Users/felipedelpozo/Sites/sample/lib/model/doctrine/User.class.php',
  'usertable' => '/Users/felipedelpozo/Sites/sample/lib/model/doctrine/UserTable.class.php',

  // application
  'myuser' => '/Users/felipedelpozo/Sites/sample/apps/frontend/lib/myUser.class.php',

  // modules
);
