<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/17 14:08:13

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=sample',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
