<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2012/02/17 14:08:13
sfConfig::add(array(
  'app_ds_ext_direct_plugin_router_url' => '/extdirect.php',
  'app_ds_ext_direct_plugin_action_namespace' => 'SAMPLE',
  'app_ds_ext_direct_plugin_js_var' => 'Ext.app.EXTDIRECT_API',
  'app_ds_ext_direct_plugin_provider_type' => 'remoting',
  'app_ds_ext_direct_plugin_include_plugins' => NULL,
));
